#APACHE
server:
  port: 8070


#EUREKA
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#H2
datasource:
  url: jdbc:h2:mem:pruebas
  username: root
  password: root

#JPA
  spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
  spring.jpa.generate-ddl=true
  spring.jpa.show-sql=true
  spring.jpa.hibernate.ddl-auto=update
  spring.jpa.hibernate.naming.strategy=org.hibernate.cfg.ImprovedNamingStrategy
  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

  spring.h2.console.enabled=true
  spring.h2.console.path=/h2-console